# -*- coding: utf-8 -*-
"""Google_Ads_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ddBBxuFKWasmkXoY6Q6vgD2Fp2zf-seI
"""

import pandas as pd
import numpy as np
from IPython.display import display
df = pd.read_csv('GoogleAds_Data_Marketing.csv')

#Объявления
#Определение самых успешных объявлений по ROI
keyword_roi = df.groupby('Ad_ID')['ROI%'].mean()
top_10_keywords = keyword_roi.sort_values(ascending=False).head(10)
#Определение самых успешных объявлений по CTR
ads_ctr = df.groupby('Ad_ID')['CTR'].mean()
top_10_ads = ads_ctr.sort_values(ascending=False).head(10)
#Определение самых успешных объявлений по CPS
keyword_cps = df.groupby('Ad_ID')['CPS'].mean()
top_10_keywords2 = keyword_cps.sort_values(ascending=True).head(10)
#Сортируем с двумя самыми важными параметрами ROI и CPS
best_ads = df.sort_values(by=['ROI%', 'CPS'], ascending=[False, True])


#Определение самых лучших ключевых слов по ROI
keyword_roi_sum = df.groupby('Keyword')['ROI%'].sum()
keyword_roi_sum

#Анализ ставок
best_ads = df.sort_values(by=['ROI%', 'CPS'], ascending=[False, True]).head(100)

#Анализ по дате
daily_cpm = df.groupby('Ad_Date')['CPM'].mean()
dates_with_low_cpm = daily_cpm.sort_values(ascending=True)
dates_with_low_cpm.to_excel('2_dates.xlsx', index=True)

daily_roi = df.groupby('Ad_Date')['ROI%'].mean()
dates_roi = daily_roi.sort_values(ascending=False)
dates_roi.to_excel('roi_dates.xlsx', index=True)