# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UtzyH55lesLJLenNCzb9a7xb5WDTZGwU
"""

#старт
import pandas as pd
import numpy as np
from IPython.display import display
df = pd.read_csv('GoogleAds_Data_Cleaned.csv')

#новый столбец CPM
df['CPM'] = (df['Cost,$'] / df['Impressions']) * 1000

#новый столбец CTR
df['CTR'] = (df['Clicks'] / df['Impressions']) * 100

#новый столбец CPC
df['CPC'] = (df['Cost,$'] / df['Clicks'])

#новый столбец CPS
df['CPS'] = (df['Cost,$'] / df['Conversions'])

#новый столбец ROI
df['ROI%'] = ((df['Sale_Amount,$'] - df['Cost,$']) / df['Cost,$']) * 100

df.to_csv('GoogleAds_Data_Marketing.csv', index=False)
pd.read_csv('GoogleAds_Data_Marketing.csv')